apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ndu9w3rkl-go 
  janus-idp.io/tekton: ndu9w3rkl-go
  backstage.io/kubernetes-id: ndu9w3rkl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ndu9w3rkl-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  