apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ndu9w3rkl-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ndu9w3rkl-go 
  name: ndu9w3rkl-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ndu9w3rkl-go 
